### PR TITLE
Add more API actions

### PR DESCRIPTION
**Pull request by davispuh**
There are much more API actions and so add some. Even these probably aren't all. Quite good documentation can find [NeweggMobileAPI](/bemasher/NeweggMobileAPI)

Also by the way, Newegg have Android app and it uses same API endpoint, but seems it uses different actions. Anyway would be nice to add all so can see which calls give most useful information.

### CODE REVIEW

**Comment by chrismagnacca** [comment]
I apologize for the delay in getting to this PR as I have been busy over the holidays. I will take a look into the issue it seems to have with Travis tonight. Otherwise, everything looks great and I will merge this into master once I iron out Travis. I agree that adding the other actions would be desirable as well. Would it be possible to add some test coverage (or update existing tests) for some of this new functionality? The test coverage is a nice to have when there are shifts in the API itself. 

I will take a look into this this evening and if the current tests are passing I will see about updating/adding test coverage prior to merging this in. I appreciate the interest as this particular project is a fun side project of mine. Thanks!

**Comment by chrismagnacca** [comment]
I've pulled down the PR and everything looks solid. The Travis issue is an unrelated issue that I've fixed up with PR#6 after merging PR#4 into master. If you update this branch off master, all current specs should be passing. I would still like to see some test coverage around these additions, but I can handle adding them later on, as these additions are rather nice. If you get time and would like to add spec coverage, please feel free to and I will accept the tests as well. Thanks!

**Comment by davispuh** [comment]
No worries. I'm busy myself aswell. I'll probably send some more PRs later and when I'll have time I'll create tests too.

**Comment by chrismagnacca** [comment]
Sounds good! Thanks for your interest! I appreciate all of the additions. :D

**Pull request merged**
